### ISSUE TITLE
add ripgrep to requirements

### ISSUE THREAD

**Issue by tobyShandy** [uriel1998/quite-intriguing#1]
Hi,

Your "quite-intriguing" looks quite interesting but you forgot to put `ripgrep` in the requirements. 
As far as I know, `ripgrep` does not usually come by default on any system.
Alternatively, you could replace it with regular `grep` --- speed is probably not an issue here, and using `grep` would increase portability.

**Comment by uriel1998** [comment]
Whoops. Thanks; silly mistake on my part.  Easier to just swap it to grep as you noted.  Fixed in v1.0.1.
