### ISSUE TITLE
Scroll through the preview window?

### ISSUE THREAD

**Issue by Barbaross93** [uriel1998/quite-intriguing#2]
Maybe I missed something, but is it possible to scroll within the fzf preview window? It seems like its possible to do: https://github.com/junegunn/fzf.vim/issues/211, but requires setting up specific key bindings

**Comment by uriel1998** [comment]
You're absolutely correct that it's a fzf thing.  I actually was going to write about how to edit this in the script when I found [here](https://www.mankier.com/1/fzf#Key/Event_Bindings-Available_Actions) that there _are_ default keybinds for that:  shift-up and shift-down .  I'll put that in the docs now.  Thanks, I learned something!
